# Generated by Django 4.1.6 on 2023-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('poblacion', models.DateField()),
                ('graduado', models.BooleanField()),
            ],
        ),
    ]
