# Generated by Django 4.1.6 on 2023-04-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('poblacion', models.DateField()),
                ('graduado', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Alum',
        ),
    ]
