# Generated by Django 4.1.6 on 2023-04-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0002_prof_rename_person_alum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alum',
            old_name='graduado',
            new_name='clase',
        ),
        migrations.RenameField(
            model_name='prof',
            old_name='graduado',
            new_name='clase',
        ),
    ]
