# Generated by Django 4.1.6 on 2023-04-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0003_rename_graduado_alum_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alum',
            name='clase',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prof',
            name='clase',
            field=models.CharField(max_length=50),
        ),
    ]
